apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ecjn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-ecjn@sha256:ffdcd74711efe02c13a8e7586ba065f96d4071b00988f6a5efcac8c4c29291c8
        name: my-nodejs
        resources: {}
status: {}
